general:
  standardName: app
  namespace: default

serviceAccount:
  name: backend-sa

deployment:
  label:
    key: app
    value: app-api
  replicas: 1
  container:
    name: app-container
    image: ghcr.io/leodom01/xm_0091-software_containerization_app:latest
    port: 8000
  hpa: 
    minReplicas: 1
    maxReplicas: 10
    resourceType: cpu
    averageValue: 50m

svc:
  type: NodePort
  protocol: TCP
  nodePort: 30001
  containerPort: 8000
  exposedPort: 8081

configMap:
  - key: MONGODB_USER
    value: our_user
  - key: MONGODB_HOST
    value: mongo-svc.default.svc.cluster.local
  - key: MONGODB_PORT
    value: 30003
  - key: MONGODB_DB
    value: appDb

secret:
  key: MONGODB_PW
  value: cGFzc3dvcmQ=
