general:
  standardName: presentation

configMap: 
  vueKey: VUE_APP_API_URI
  vueHost: app-service.default.svc.cluster.local
  vuePort: 8081

deployment: 
  label: 
    key: app
    value: presentation 
  replicas: 1
  container: 
    name: presentation-container
    image: ghcr.io/leodom01/xm_0091-software_containerization_presentation:latest
    containerPort: 80
  env:
    varName: VUE_APP_API_URI
    configMapRefName: presentation-config

svc:
  type: NodePort
  port:
    protocol: TCP
    containerPort: 80
    nodePort: 30002
    clusterPort: 8091

