apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.general.standardName }}-deployment
  labels:
    {{ .Values.deployment.label.key }}: {{ .Values.deployment.label.value }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{ .Values.deployment.label.key }}: {{ .Values.deployment.label.value }}
  template:
    metadata:
      labels:
        {{ .Values.deployment.label.key }}: {{ .Values.deployment.label.value }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: {{ .Values.global.images.presentationTier  }}
          ports:
            - containerPort: {{ .Values.deployment.container.containerPort }}
          env:
            - name: {{ .Values.deployment.env.varUriName }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.deployment.env.configMapRefName }}
                  key: {{ .Values.deployment.env.varUriName }}
            - name: {{ .Values.deployment.env.varPortName }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.deployment.env.configMapRefName }}
                  key: {{ .Values.deployment.env.varPortName }}
