apiVersion: apps/v1
kind: Deployment
metadata:
  name: reminders-deployment
spec:
  replicas: 3  # Adjust as needed
  selector:
    matchLabels:
      app: reminders
  template:
    metadata:
      labels:
        app: reminders
    spec:
      containers:
      - name: reminders-ui
        image: ghcr.io/leodom01/xm_0091-software_containerization_presentation:latest
        ports:
        - containerPort: 80
