apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: db-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: db-sa
    namespace: default
roleRef:
  kind: Role
  name: db-role
  apiGroup: rbac.authorization.k8s.io
