general:
  standardName: presentation
  namespace: default

configMap:
  vueHostKey: VUE_APP_API_URI
  vueHost: app-svc
  vuePortKey: VUE_APP_API_PORT
  vuePort: 8081

serviceAccount:
  name: frontend-sa

deployment:
  label:
    key: app
    value: presentation
  replicas: 1
  container:
    name: presentation-container
    image: ghcr.io/leodom01/xm_0091-software_containerization_presentation:latest
    containerPort: 80
  env:
    varUriName: VUE_APP_API_URI
    varPortName: VUE_APP_API_PORT
    configMapRefName: presentation-config

svc:
  type: NodePort
  port:
    protocol: TCP
    containerPort: 80
    nodePort: 30002
    clusterPort: 8091
