general:
  standardName: presentation
<<<<<<< HEAD
=======
  namespace: default
>>>>>>> fab5f5b (moved charts into app-deployment, renamed rbac to rbac-chart)

configMap:
  vueHostKey: VUE_APP_API_URI
  vueHost: app-svc
  vuePortKey: VUE_APP_API_PORT
  vuePort: 8081

<<<<<<< HEAD
=======
serviceAccount:
  name: frontend-sa

>>>>>>> fab5f5b (moved charts into app-deployment, renamed rbac to rbac-chart)
deployment:
  label:
    key: app
    value: presentation
  replicas: 1
  container:
    name: presentation-container
    image: ghcr.io/leodom01/xm_0091-software_containerization_presentation:latest
    containerPort: 80
  env:
    varUriName: VUE_APP_API_URI
    varPortName: VUE_APP_API_PORT
    configMapRefName: presentation-config
<<<<<<< HEAD
  serviceAccountName: frontend-sa
  namespace: default
=======
>>>>>>> fab5f5b (moved charts into app-deployment, renamed rbac to rbac-chart)

svc:
  type: NodePort
  port:
    protocol: TCP
    containerPort: 80
    nodePort: 30002
    clusterPort: 8091
