apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.general.standardName }}-pvc
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  storageClassName: standard-rwo