apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: {{ .Values.general.standardName }}-pvc
spec:
 storageClassName: {{ .Values.pvc.storageClassName }}
 accessModes: 
 - {{ .Values.pvc.accessModes }}
 resources:
   requests:
     storage: {{ .Values.pvc.storage }}