# Commenting since for the GCP demo we will use the dbGCPPVC.yaml instead of this 
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: {{ .Values.general.standardName }}-pvc
#spec:
#  storageClassName: {{ .Values.pvc.storageClassName }}
#  accessModes: 
#  - {{ .Values.pvc.accessModes }}
#  resources:
#    requests:
#      storage: {{ .Values.pvc.storage }}