apiVersion: apps/v1
kind: Deployment
metadata:
  name: presentation-deployment
  labels:
    app: presentation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presentation
  template:
    metadata:
      labels:
        app: presentation
    spec:
      containers:
      - name: presentation-container
        image: ghcr.io/leodom01/xm_0091-software_containerization_presentation:latest
        ports:
        - containerPort: 80