general:
  standardName: mongo
<<<<<<< HEAD
=======
  namespace: default
>>>>>>> fab5f5b (moved charts into app-deployment, renamed rbac to rbac-chart)

db:
  userKey: MONGODB_USER
  user: our_user
  pwKey: MONGODB_PW
  pw: cGFzc3dvcmQ=

pvc:
  accessModes: ReadWriteOnce
  storage: 250M
  hostPath: /opt/data
  reclaimPolicy: Retain
  storageClassName: mongodb-hostpath
  volumeMode: Filesystem

<<<<<<< HEAD
=======
serviceAccount:
  name: db-sa

>>>>>>> fab5f5b (moved charts into app-deployment, renamed rbac to rbac-chart)
stateSet:
  replicas: 1
  serviceName: db-tier
  labelKey: app
  labelValue: db-tier
  containerName: mongo
  containerImage: ghcr.io/leodom01/xm_0091-software_containerization_db:latest
  containerPort: 27017
  pvcMountPath: /data/db
<<<<<<< HEAD
  serviceAccountName: db-sa
  namespace: default
=======
>>>>>>> fab5f5b (moved charts into app-deployment, renamed rbac to rbac-chart)

svc:
  type: ClusterIP
  exposedPort: 30003
