apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.general.standardName }}-pv
spec:
  accessModes: {{ .Values.pv.accessModes }}
  capacity:
    storage: {{ .Values.pv.storage }}
  hostPath:
    path: {{ .Values.pv.hostPath }}
  persistentVolumeReclaimPolicy: {{ .Values.pv.reclaimPolicy }}
  storageClassName: {{ .Values.pv.storageClassName }}
  volumeMode: {{ .Values.pv.volumeMode }}