kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.general.standardName }}-api-allow
spec:
  podSelector:
    matchLabels:
      {{ .Values.deployment.label.key }}: {{ .Values.deployment.label.value }}-api
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.stackPods.presentationTierName }}
    - podSelector:
        matchLabels:
          app: {{ .Values.stackPods.dbTierName }}
