apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.general.standardName }}-deployment
  labels:
    {{ .Values.deployment.label.key }}: {{ .Values.deployment.label.value }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{ .Values.deployment.label.key }}: {{ .Values.deployment.label.value }}
  template:
    metadata:
      labels:
        {{ .Values.deployment.label.key }}: {{ .Values.deployment.label.value }}
    spec:
      serviceAccountName: {{ .Values.general.serviceAccountName }}
      containers:
      - name: {{ .Values.deployment.container.name }}
        image: {{ .Values.deployment.container.image }}
        ports:
        - containerPort: {{ .Values.deployment.container.port }}
        env:
        {{- range $item := .Values.configMap}}
        - name: {{ $item.key }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Values.general.standardName }}-config
              key: {{ $item.key }}
        {{- end}}
        - name: {{ .Values.secret.key }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.general.standardName }}-secret
              key: {{ .Values.secret.key }}