kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: presentation-allow
spec:
  podSelector:
    matchLabels:
      app: presentation
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: app-api
    - podSelector:
        matchLabels:
          app: db-tier

