apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  accessModes: 
  - ReadWriteOnce
  capacity:
    storage: 250M
  hostPath:
    path: /opt/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-hostpath
  volumeMode: Filesystem