apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1000Mi
  hostPath:
    path: /appPersistentStorage/db
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem