apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: backend-role
rules:
  - apiGroups: [""]
    resources:
      [
        "pods",
        "services",
        "deployments",
        "networkpolicies",
        "configmaps",
        "secrets",
      ]
    verbs: ["get", "list", "watch"]
